dsn: postgresql://postgres:postgres@localhost:5432/app?sslmode=disable
docPath: ./docs
er:
  format: mermaid
dict:
  Tables: テーブル一覧
  Description: 概要
  Columns: カラム一覧
  Indexes: INDEX一覧
  Constraints: 制約一覧
  Triggers: トリガー
  Relations: ER図
  Name: 名前
  Comment: コメント
  Type: タイプ
  Default: デフォルト値
  Children: 子テーブル
  Parents: 親テーブル
  Definition: 定義
  Table Definition: テーブル定義

lint: 
  requireTableComment: 
    enabled: true
  requireColumnComment: 
    enabled: true
    exclude:
      - id
  requireViewpoints: 
    enabled: true
lintExclude:
  - _prisma_migrations
viewpoints:
  -
    name: 書籍の追加
    desc: 書籍を追加する際に関連するテーブルのまとまり
    tables:
      - books
      - products
      - publishers
      - authors
      - author_books
      - book_images

  - 
    name: 顧客の追加
    desc: 顧客を追加する際に関連するテーブルのまとまり
    tables:
      - customers

  - 
    name: 配送先の追加
    desc: 配送先を追加する際に関連するテーブルのまとまり
    tables:
      - shipping_addresses
      - customers

  - 
    name: 書籍の購入
    desc: 
      書籍を購入する際に関連するテーブルのまとまり。
      顧客が購入できるためには、配送先が設定される必要がある。
      配送時に参照される製品コードはproductsテーブルから取得される。
    tables:
      - books
      - products
      - customers
      - shipping_addresses
      - orders
      - order_items

  